// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: dagpool.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DagPoolClient is the client API for DagPool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DagPoolClient interface {
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddReply, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetReply, error)
	Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveReply, error)
	GetSize(ctx context.Context, in *GetSizeReq, opts ...grpc.CallOption) (*GetSizeReply, error)
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserReply, error)
	RemoveUser(ctx context.Context, in *RemoveUserReq, opts ...grpc.CallOption) (*RemoveUserReply, error)
	QueryUser(ctx context.Context, in *QueryUserReq, opts ...grpc.CallOption) (*QueryUserReply, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserReply, error)
}

type dagPoolClient struct {
	cc grpc.ClientConnInterface
}

func NewDagPoolClient(cc grpc.ClientConnInterface) DagPoolClient {
	return &dagPoolClient{cc}
}

func (c *dagPoolClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveReply, error) {
	out := new(RemoveReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) GetSize(ctx context.Context, in *GetSizeReq, opts ...grpc.CallOption) (*GetSizeReply, error) {
	out := new(GetSizeReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/GetSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserReply, error) {
	out := new(AddUserReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) RemoveUser(ctx context.Context, in *RemoveUserReq, opts ...grpc.CallOption) (*RemoveUserReply, error) {
	out := new(RemoveUserReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/RemoveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) QueryUser(ctx context.Context, in *QueryUserReq, opts ...grpc.CallOption) (*QueryUserReply, error) {
	out := new(QueryUserReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/QueryUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserReply, error) {
	out := new(UpdateUserReply)
	err := c.cc.Invoke(ctx, "/proto.DagPool/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DagPoolServer is the server API for DagPool service.
// All implementations must embed UnimplementedDagPoolServer
// for forward compatibility
type DagPoolServer interface {
	Add(context.Context, *AddReq) (*AddReply, error)
	Get(context.Context, *GetReq) (*GetReply, error)
	Remove(context.Context, *RemoveReq) (*RemoveReply, error)
	GetSize(context.Context, *GetSizeReq) (*GetSizeReply, error)
	AddUser(context.Context, *AddUserReq) (*AddUserReply, error)
	RemoveUser(context.Context, *RemoveUserReq) (*RemoveUserReply, error)
	QueryUser(context.Context, *QueryUserReq) (*QueryUserReply, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserReply, error)
	mustEmbedUnimplementedDagPoolServer()
}

// UnimplementedDagPoolServer must be embedded to have forward compatible implementations.
type UnimplementedDagPoolServer struct {
}

func (UnimplementedDagPoolServer) Add(context.Context, *AddReq) (*AddReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedDagPoolServer) Get(context.Context, *GetReq) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDagPoolServer) Remove(context.Context, *RemoveReq) (*RemoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedDagPoolServer) GetSize(context.Context, *GetSizeReq) (*GetSizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSize not implemented")
}
func (UnimplementedDagPoolServer) AddUser(context.Context, *AddUserReq) (*AddUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedDagPoolServer) RemoveUser(context.Context, *RemoveUserReq) (*RemoveUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedDagPoolServer) QueryUser(context.Context, *QueryUserReq) (*QueryUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUser not implemented")
}
func (UnimplementedDagPoolServer) UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedDagPoolServer) mustEmbedUnimplementedDagPoolServer() {}

// UnsafeDagPoolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DagPoolServer will
// result in compilation errors.
type UnsafeDagPoolServer interface {
	mustEmbedUnimplementedDagPoolServer()
}

func RegisterDagPoolServer(s grpc.ServiceRegistrar, srv DagPoolServer) {
	s.RegisterService(&DagPool_ServiceDesc, srv)
}

func _DagPool_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).Remove(ctx, req.(*RemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_GetSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).GetSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/GetSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).GetSize(ctx, req.(*GetSizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/RemoveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).RemoveUser(ctx, req.(*RemoveUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_QueryUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).QueryUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/QueryUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).QueryUser(ctx, req.(*QueryUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPool_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPool/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DagPool_ServiceDesc is the grpc.ServiceDesc for DagPool service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DagPool_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DagPool",
	HandlerType: (*DagPoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _DagPool_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DagPool_Get_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DagPool_Remove_Handler,
		},
		{
			MethodName: "GetSize",
			Handler:    _DagPool_GetSize_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _DagPool_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _DagPool_RemoveUser_Handler,
		},
		{
			MethodName: "QueryUser",
			Handler:    _DagPool_QueryUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _DagPool_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dagpool.proto",
}

// DagPoolClusterClient is the client API for DagPoolCluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DagPoolClusterClient interface {
	InitSlots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddDagNode(ctx context.Context, in *DagNodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDagNode(ctx context.Context, in *GetDagNodeReq, opts ...grpc.CallOption) (*DagNodeInfo, error)
	RemoveDagNode(ctx context.Context, in *RemoveDagNodeReq, opts ...grpc.CallOption) (*DagNodeInfo, error)
	MigrateSlots(ctx context.Context, in *MigrateSlotsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BalanceSlots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusReply, error)
}

type dagPoolClusterClient struct {
	cc grpc.ClientConnInterface
}

func NewDagPoolClusterClient(cc grpc.ClientConnInterface) DagPoolClusterClient {
	return &dagPoolClusterClient{cc}
}

func (c *dagPoolClusterClient) InitSlots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/InitSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClusterClient) AddDagNode(ctx context.Context, in *DagNodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/AddDagNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClusterClient) GetDagNode(ctx context.Context, in *GetDagNodeReq, opts ...grpc.CallOption) (*DagNodeInfo, error) {
	out := new(DagNodeInfo)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/GetDagNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClusterClient) RemoveDagNode(ctx context.Context, in *RemoveDagNodeReq, opts ...grpc.CallOption) (*DagNodeInfo, error) {
	out := new(DagNodeInfo)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/RemoveDagNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClusterClient) MigrateSlots(ctx context.Context, in *MigrateSlotsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/MigrateSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClusterClient) BalanceSlots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/BalanceSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dagPoolClusterClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/proto.DagPoolCluster/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DagPoolClusterServer is the server API for DagPoolCluster service.
// All implementations must embed UnimplementedDagPoolClusterServer
// for forward compatibility
type DagPoolClusterServer interface {
	InitSlots(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	AddDagNode(context.Context, *DagNodeInfo) (*emptypb.Empty, error)
	GetDagNode(context.Context, *GetDagNodeReq) (*DagNodeInfo, error)
	RemoveDagNode(context.Context, *RemoveDagNodeReq) (*DagNodeInfo, error)
	MigrateSlots(context.Context, *MigrateSlotsReq) (*emptypb.Empty, error)
	BalanceSlots(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	Status(context.Context, *emptypb.Empty) (*StatusReply, error)
	mustEmbedUnimplementedDagPoolClusterServer()
}

// UnimplementedDagPoolClusterServer must be embedded to have forward compatible implementations.
type UnimplementedDagPoolClusterServer struct {
}

func (UnimplementedDagPoolClusterServer) InitSlots(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitSlots not implemented")
}
func (UnimplementedDagPoolClusterServer) AddDagNode(context.Context, *DagNodeInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDagNode not implemented")
}
func (UnimplementedDagPoolClusterServer) GetDagNode(context.Context, *GetDagNodeReq) (*DagNodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDagNode not implemented")
}
func (UnimplementedDagPoolClusterServer) RemoveDagNode(context.Context, *RemoveDagNodeReq) (*DagNodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDagNode not implemented")
}
func (UnimplementedDagPoolClusterServer) MigrateSlots(context.Context, *MigrateSlotsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateSlots not implemented")
}
func (UnimplementedDagPoolClusterServer) BalanceSlots(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BalanceSlots not implemented")
}
func (UnimplementedDagPoolClusterServer) Status(context.Context, *emptypb.Empty) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDagPoolClusterServer) mustEmbedUnimplementedDagPoolClusterServer() {}

// UnsafeDagPoolClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DagPoolClusterServer will
// result in compilation errors.
type UnsafeDagPoolClusterServer interface {
	mustEmbedUnimplementedDagPoolClusterServer()
}

func RegisterDagPoolClusterServer(s grpc.ServiceRegistrar, srv DagPoolClusterServer) {
	s.RegisterService(&DagPoolCluster_ServiceDesc, srv)
}

func _DagPoolCluster_InitSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).InitSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/InitSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).InitSlots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPoolCluster_AddDagNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DagNodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).AddDagNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/AddDagNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).AddDagNode(ctx, req.(*DagNodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPoolCluster_GetDagNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDagNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).GetDagNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/GetDagNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).GetDagNode(ctx, req.(*GetDagNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPoolCluster_RemoveDagNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDagNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).RemoveDagNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/RemoveDagNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).RemoveDagNode(ctx, req.(*RemoveDagNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPoolCluster_MigrateSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateSlotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).MigrateSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/MigrateSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).MigrateSlots(ctx, req.(*MigrateSlotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPoolCluster_BalanceSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).BalanceSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/BalanceSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).BalanceSlots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DagPoolCluster_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DagPoolClusterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DagPoolCluster/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DagPoolClusterServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DagPoolCluster_ServiceDesc is the grpc.ServiceDesc for DagPoolCluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DagPoolCluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DagPoolCluster",
	HandlerType: (*DagPoolClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitSlots",
			Handler:    _DagPoolCluster_InitSlots_Handler,
		},
		{
			MethodName: "AddDagNode",
			Handler:    _DagPoolCluster_AddDagNode_Handler,
		},
		{
			MethodName: "GetDagNode",
			Handler:    _DagPoolCluster_GetDagNode_Handler,
		},
		{
			MethodName: "RemoveDagNode",
			Handler:    _DagPoolCluster_RemoveDagNode_Handler,
		},
		{
			MethodName: "MigrateSlots",
			Handler:    _DagPoolCluster_MigrateSlots_Handler,
		},
		{
			MethodName: "BalanceSlots",
			Handler:    _DagPoolCluster_BalanceSlots_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _DagPoolCluster_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dagpool.proto",
}
