package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"github.com/filedag-project/filedag-storage/http/console/models"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddUserHandlerFunc turns a function with the right signature into a add user handler
type AddUserHandlerFunc func(AddUserParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddUserHandlerFunc) Handle(params AddUserParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddUserHandler interface for that can handle valid add user params
type AddUserHandler interface {
	Handle(AddUserParams, *models.Principal) middleware.Responder
}

// NewAddUser creates a new http.Handler for the add user operation
func NewAddUser(ctx *middleware.Context, handler AddUserHandler) *AddUser {
	return &AddUser{Context: ctx, Handler: handler}
}

/* AddUser swagger:route POST /users AdminAPI addUser

Add User

*/
type AddUser struct {
	Context *middleware.Context
	Handler AddUserHandler
}

func (o *AddUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
