package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"github.com/filedag-project/filedag-storage/http/console/models"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RemoveUserHandlerFunc turns a function with the right signature into a remove user handler
type RemoveUserHandlerFunc func(RemoveUserParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveUserHandlerFunc) Handle(params RemoveUserParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// RemoveUserHandler interface for that can handle valid remove user params
type RemoveUserHandler interface {
	Handle(RemoveUserParams, *models.Principal) middleware.Responder
}

// NewRemoveUser creates a new http.Handler for the remove user operation
func NewRemoveUser(ctx *middleware.Context, handler RemoveUserHandler) *RemoveUser {
	return &RemoveUser{Context: ctx, Handler: handler}
}

/* RemoveUser swagger:route DELETE /user AdminAPI removeUser

Remove user

*/
type RemoveUser struct {
	Context *middleware.Context
	Handler RemoveUserHandler
}

func (o *RemoveUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRemoveUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
