// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/filedag-project/filedag-storage/dag/pool (interfaces: DagPool)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dpuser "github.com/filedag-project/filedag-storage/dag/pool/poolservice/dpuser"
	gomock "github.com/golang/mock/gomock"
	blocks "github.com/ipfs/go-block-format"
	cid "github.com/ipfs/go-cid"
)

// MockDagPool is a mock of DagPool interface.
type MockDagPool struct {
	ctrl     *gomock.Controller
	recorder *MockDagPoolMockRecorder
}

// MockDagPoolMockRecorder is the mock recorder for MockDagPool.
type MockDagPoolMockRecorder struct {
	mock *MockDagPool
}

// NewMockDagPool creates a new mock instance.
func NewMockDagPool(ctrl *gomock.Controller) *MockDagPool {
	mock := &MockDagPool{ctrl: ctrl}
	mock.recorder = &MockDagPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDagPool) EXPECT() *MockDagPoolMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockDagPool) Add(arg0 context.Context, arg1 blocks.Block, arg2, arg3 string, arg4 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockDagPoolMockRecorder) Add(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockDagPool)(nil).Add), arg0, arg1, arg2, arg3, arg4)
}

// AddUser mocks base method.
func (m *MockDagPool) AddUser(arg0 dpuser.DagPoolUser, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockDagPoolMockRecorder) AddUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockDagPool)(nil).AddUser), arg0, arg1, arg2)
}

// Close mocks base method.
func (m *MockDagPool) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDagPoolMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDagPool)(nil).Close))
}

// Get mocks base method.
func (m *MockDagPool) Get(arg0 context.Context, arg1 cid.Cid, arg2, arg3 string) (blocks.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(blocks.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDagPoolMockRecorder) Get(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDagPool)(nil).Get), arg0, arg1, arg2, arg3)
}

// GetSize mocks base method.
func (m *MockDagPool) GetSize(arg0 context.Context, arg1 cid.Cid, arg2, arg3 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSize", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSize indicates an expected call of GetSize.
func (mr *MockDagPoolMockRecorder) GetSize(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSize", reflect.TypeOf((*MockDagPool)(nil).GetSize), arg0, arg1, arg2, arg3)
}

// Pin mocks base method.
func (m *MockDagPool) Pin(arg0 context.Context, arg1 cid.Cid, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pin", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pin indicates an expected call of Pin.
func (mr *MockDagPoolMockRecorder) Pin(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pin", reflect.TypeOf((*MockDagPool)(nil).Pin), arg0, arg1, arg2, arg3)
}

// QueryUser mocks base method.
func (m *MockDagPool) QueryUser(arg0, arg1, arg2 string) (*dpuser.DagPoolUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dpuser.DagPoolUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUser indicates an expected call of QueryUser.
func (mr *MockDagPoolMockRecorder) QueryUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUser", reflect.TypeOf((*MockDagPool)(nil).QueryUser), arg0, arg1, arg2)
}

// Remove mocks base method.
func (m *MockDagPool) Remove(arg0 context.Context, arg1 cid.Cid, arg2, arg3 string, arg4 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockDagPoolMockRecorder) Remove(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockDagPool)(nil).Remove), arg0, arg1, arg2, arg3, arg4)
}

// RemoveUser mocks base method.
func (m *MockDagPool) RemoveUser(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockDagPoolMockRecorder) RemoveUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockDagPool)(nil).RemoveUser), arg0, arg1, arg2)
}

// UnPin mocks base method.
func (m *MockDagPool) UnPin(arg0 context.Context, arg1 cid.Cid, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnPin", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnPin indicates an expected call of UnPin.
func (mr *MockDagPoolMockRecorder) UnPin(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnPin", reflect.TypeOf((*MockDagPool)(nil).UnPin), arg0, arg1, arg2, arg3)
}

// UpdateUser mocks base method.
func (m *MockDagPool) UpdateUser(arg0 dpuser.DagPoolUser, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockDagPoolMockRecorder) UpdateUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockDagPool)(nil).UpdateUser), arg0, arg1, arg2)
}
