package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// BucketAccess bucket access
//
// swagger:model bucketAccess
type BucketAccess string

func NewBucketAccess(value BucketAccess) *BucketAccess {
	return &value
}

// Pointer returns a pointer to a freshly-allocated BucketAccess.
func (m BucketAccess) Pointer() *BucketAccess {
	return &m
}

const (

	// BucketAccessPRIVATE captures enum value "PRIVATE"
	BucketAccessPRIVATE BucketAccess = "PRIVATE"

	// BucketAccessPUBLIC captures enum value "PUBLIC"
	BucketAccessPUBLIC BucketAccess = "PUBLIC"

	// BucketAccessCUSTOM captures enum value "CUSTOM"
	BucketAccessCUSTOM BucketAccess = "CUSTOM"
)

// for schema
var bucketAccessEnum []interface{}

func init() {
	var res []BucketAccess
	if err := json.Unmarshal([]byte(`["PRIVATE","PUBLIC","CUSTOM"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		bucketAccessEnum = append(bucketAccessEnum, v)
	}
}

func (m BucketAccess) validateBucketAccessEnum(path, location string, value BucketAccess) error {
	if err := validate.EnumCase(path, location, value, bucketAccessEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this bucket access
func (m BucketAccess) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateBucketAccessEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this bucket access based on context it is used
func (m BucketAccess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
