package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

type SetUserPolicyParams struct {

	// access
	// Required: true
	Name string `json:"name"`

	// access
	// Required: true
	Access *BucketAccess `json:"access"`

	// definition
	Definition string `json:"definition,omitempty"`
}
